### ISSUE TITLE
Clarify usage

### ISSUE THREAD

**Issue by aleksejrs** [lovac42/Cardistry#2]
This is not enough:

```
# Configs:
Enable using deck menu options.  

0 = disable  
200 = about 10 young cards daily (200/20)  
200 young/learning/new cards spread across 20 days.
```

Sure, I have been using [OneLessDraw](https://github.com/lovac42/OneLessDraw), so using todays' New numbers is probably unhelpful, but it's still hard to understand from the text itself what the right way to use it would be.

* Does it consider only the cards that are or will become due in the deck configured and its subdecks?  Or only the ones in the deck configured?
* If I set the number to "200", the "New (Unseen)" number becomes "63 (+3)", which is obviously too many with my backlog of almost 1000. So apparently the current instruction cited above says that, if you want to have 200 young+new cards in your collection, you need to divide 200 by 20, and put the result into the "New/Young Cards" field (that label confused me because of the unclear manual: I thought it could be "New" divided by "Young"), and the "200" is not a field value, unlike the "0".
* So, if I already have had 400 reviews per day on average this year, should I put 400÷20 = *20* into the field to be sure I don't get more to review (or, probably better, based on this month, 281 ÷ 20 = *14*)?  Actually, only 0.348 of my reviews are of Young or New cards, and I would have to do more calculation to find out how many of those *cards* are Young or New.
* I have 840 Young cards in that deck and its subdecks. "Progress Graphs and Stats for Learned and Matured Cards" says that 30 cards mature per day, on average, in my collection (including the deleted cards).  Matured Cards Lost + Net Matured Cards is also 30 (depending on the time of day, it can be 27 to 30).  840/30,49 = 27,55 which is what I set the new card limit to, but it has rarely been reached because of OneLessDraw and the backlog (though reviews and new cards have been mixed).  Progress graph says 138 cards learned in the past month, which is 4.53 cards/day.

**Comment by lovac42** [comment]
This addon scans cards with an interval of less than 21 days (young card) PER DECK based on profile settings.

So if you want 200 young cards, and you currently have 190, you will need to review 10 new cards today.
If you have 195, you will have 5 new cards today. But if 3 matured and 2 lapsed, they will be adjusted. This is a gradual process, it doesn't happen over night. Over time, you will get on average 20 young cards per day, a bit more in the first week.
