### ISSUE TITLE
Debug info to see why a deck has no new cards left?

### ISSUE THREAD

**Issue by aleksejrs** [lovac42/Cardistry#5]
I've made a complex deck tree, and now I can't understand why some decks have no new cards left to review.

Since it's a tree, decks are supposed to restrict each other, but I am not sure which restrictions are inherited.
I thought it was only the ordinary New Card Limit, but it's hard to find out using the add-ons I have how many cards I have in each deck, and the numbers **seem** to show that I learned less than those limits.
Can Cardistry's limits be inherited? That's why "PER DECK" was confusing to me.

**Comment by lovac42** [comment]
The limit per deck is set by Anki. It asks each subdeck for the count number. So affecting parent decks won't be possible without a huge amount of effort.

But anki already keeps a running count of each decks new/reviews. So we could just print those infos out. This file will print out the info for the current SELECTED deck and all subdecks. It addes a menu to "Study" and shows an editor when you click it. Text is in CSV, so you can import to excel. https://github.com/lovac42/Cardistry/tree/debuginfo/src

format is:
New ;; Review ;; DID ;; Deck_Name

**Comment by aleksejrs** [comment]
Even without the deck tree, there is some confusion adding to the problem (maybe through accumulation): at what point does the limit take effect?

So, I think it became impossible to view `New cards` after this line came to this:
`0011;;00029;;1528973653224;;/::s::0-de`

Cardistry setting: `New/Young Cards: 200` (I think the "New" there is misleading, e.g. `is:new -is:suspended -is:buried` for the deck is 77 cards)
Info from Enhance_main_window.py, I think? `Learning now (later): 5 (+1)`

`deck:current  (-deck:/::s::*::* deck:/::s*) prop:ivl<23 -is:suspended -is:new`
200 cards
`deck:current  (-deck:/::s::*::* deck:/::s*) prop:ivl<22 -is:suspended -is:new`
197 cards
`deck:current  (-deck:/::s::*::* deck:/::s*) prop:ivl<21 -is:suspended -is:new`
190 cards
`deck:current  (-deck:/::s::*::* deck:/::s*) prop:ivl<20 -is:suspended -is:new`
179 cards

**Comment by aleksejrs** [comment]
> The limit per deck is set by Anki. It asks each subdeck for the count number.

Does the add-on ask Anki for the introducable card amount for each deck?

Sorry about writing while sleepy, but otherwise I would forget to:
IIUC now, when a deck has a big New Card limit, but its Cardistry limit is used up, the deck's subdecks will have nothing left no matter their settings unless they are moved to a different parent deck (or maybe are affected by Custom Study).

**Comment by aleksejrs** [comment]
I suppose some arithmetics could be used to find out (based on https://github.com/Arthur-Milchior/anki-enhance-main-window) what limits could be increased to get more new cards for today for a given deck.

`anki-enhance-main-window` already has `"Do not count subdeck's card"` that can be set to `True`.

**Comment by lovac42** [comment]
Looks interesting, feel free to PR if you get it working.
